# Site settings
title: "JBullrich"
bye_message: "Thx!"
baseurl: "/GameDev/"
url: "https://bullrich.github.io"
disqus: gamedev-javyer
analytics: "UA-98512154-1"
images: /images/games/

# Header settings
nick: "jbullrich"
main_site:
    domain: "bullrich"
    ext: "github.io"
source_code:
    server: "github.com"
    nick: "bullrich"
blog:
    server: "wordpress.com"
    nick: "gjuniioor"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

collections:
  games:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
